
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 16 07:26:22 GMT-05:00 2016
//----------------------------------------------------

package comp;

/** CUP generated interface containing symbol constants. */
public interface GeneradorSym {
  /* terminals */
  public static final int LLAV_AB = 5;
  public static final int OP_UNARIO_MENOS = 13;
  public static final int CHAR = 35;
  public static final int POR = 16;
  public static final int OUTPUT = 29;
  public static final int ENTERO = 19;
  public static final int PAR_CER = 4;
  public static final int INPUT = 28;
  public static final int OP_UNARIO_MAS = 12;
  public static final int INT = 36;
  public static final int PAR_AB = 3;
  public static final int IGUAL = 9;
  public static final int CARACTER = 18;
  public static final int COR_CER = 8;
  public static final int BOOL = 39;
  public static final int DIV = 17;
  public static final int IF = 23;
  public static final int ID = 31;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int CADENA = 21;
  public static final int MENOS = 15;
  public static final int VOID = 40;
  public static final int OP_COMP_L = 11;
  public static final int COR_AB = 7;
  public static final int DOSPUN = 33;
  public static final int ELSE = 24;
  public static final int WHILE = 26;
  public static final int FLOAT = 37;
  public static final int THEN = 25;
  public static final int END = 34;
  public static final int CARACT_ESP = 2;
  public static final int BOOLEANO = 22;
  public static final int STRING = 38;
  public static final int OP_COMP = 10;
  public static final int FLOTANTE = 20;
  public static final int DO = 27;
  public static final int LLAV_CER = 6;
  public static final int MAS = 14;
}

