
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 23:20:36 GMT-05:00 2015
//----------------------------------------------------

package comp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ELSE = 25;
  public static final int OP_BINARIO = 22;
  public static final int IGUAL = 20;
  public static final int THEN = 26;
  public static final int WHILE = 27;
  public static final int PAR_CER = 15;
  public static final int PAR_AB = 14;
  public static final int END = 11;
  public static final int COR_CER = 19;
  public static final int DOSPUN = 13;
  public static final int IF = 24;
  public static final int FLOTANTE = 5;
  public static final int OP_COMP = 23;
  public static final int ID = 10;
  public static final int TIPO = 9;
  public static final int DO = 28;
  public static final int OP_UNARIO = 21;
  public static final int CARACTER = 3;
  public static final int KEYWORD = 6;
  public static final int STRING = 7;
  public static final int COMA = 12;
  public static final int EOF = 0;
  public static final int CARACT_ESP = 2;
  public static final int error = 1;
  public static final int COR_AB = 18;
  public static final int BOOL = 8;
  public static final int ENTERO = 4;
  public static final int LLAV_CER = 17;
  public static final int LLAV_AB = 16;
}

