
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 15:03:52 GMT-05:00 2015
//----------------------------------------------------

package comp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PAR_CER = 16;
  public static final int PAR_AB = 15;
  public static final int END = 12;
  public static final int COR_CER = 20;
  public static final int DOSPUN = 14;
  public static final int FLOTANTE = 5;
  public static final int ID = 11;
  public static final int OP_COMP = 2;
  public static final int TIPO = 10;
  public static final int CARACTER = 4;
  public static final int KEYWORD = 7;
  public static final int STRING = 8;
  public static final int COMA = 13;
  public static final int EOF = 0;
  public static final int CARACT_ESP = 3;
  public static final int error = 1;
  public static final int COR_AB = 19;
  public static final int BOOL = 9;
  public static final int ENTERO = 6;
  public static final int LLAV_CER = 18;
  public static final int LLAV_AB = 17;
}

