
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 21 10:20:35 GMT-05:00 2015
//----------------------------------------------------

package comp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OP_COMP_L = 18;
  public static final int INPUT = 29;
  public static final int ELSE = 25;
  public static final int OP_BINARIO = 16;
  public static final int IGUAL = 14;
  public static final int THEN = 26;
  public static final int WHILE = 27;
  public static final int PAR_CER = 9;
  public static final int PAR_AB = 8;
  public static final int RETURN = 31;
  public static final int END = 5;
  public static final int COR_CER = 13;
  public static final int DOSPUN = 7;
  public static final int IF = 24;
  public static final int FLOTANTE = 21;
  public static final int OP_COMP = 17;
  public static final int ID = 4;
  public static final int TIPO = 3;
  public static final int DO = 28;
  public static final int CARACTER = 19;
  public static final int OP_UNARIO = 15;
  public static final int STRING = 22;
  public static final int COMA = 6;
  public static final int EOF = 0;
  public static final int CARACT_ESP = 2;
  public static final int error = 1;
  public static final int COR_AB = 12;
  public static final int BOOL = 23;
  public static final int ENTERO = 20;
  public static final int LLAV_CER = 11;
  public static final int OUTPUT = 30;
  public static final int LLAV_AB = 10;
}

